"""
================================================================================
SAD Installation Shared Helpers
================================================================================
SAD2XS: The unofficial Strategic Accelerator Design (SAD) to Xsuite converter

This file is part of the SAD2XS project, licensed under the Apache License Version 2.0.
See LICENSE for details.

Authors:    John P. T. Salvesen
Email:      john.salvesen@cern.ch
Date:       2026-08-27
================================================================================
"""
################################################################################
# Required Packages
################################################################################
import json
import logging
import os
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from pathlib import Path

logger  = logging.getLogger(__name__)

################################################################################
# Default Locations
################################################################################
SAD_GIT_REPO_URL    = "https://github.com/KatsOide/SAD.git"
SAD_GIT_BRANCH      = "master"

# git ls-remote --exit-code: the remote answered, and has no such head.
NO_MATCHING_REF     = 2

# Written inside the source tree, and only once a clone has succeeded, so it
# marks exactly the directory this installer created. A marker in the parent
# prefix would outlive its own tree and authorise deleting whatever replaced it.
INSTALL_MARKER      = ".sad2xs-install"

# A fixed name, so an install killed outright is discoverable by the next
# run. Its presence means the previous transaction did not commit.
TRANSACTION_DIR     = ".sad2xs-transaction"
TRANSACTION_RECORD  = "transaction.json"
TRANSACTION_VERSION = 1

# A committed transaction is renamed here before it is cleared up, so a
# later run can never read what is left as rollback state.
CLEANUP_PREFIX      = ".sad2xs-cleanup-"

# Carried inside every generated launcher, so an existing file can be
# identified as this installer's before it is replaced.
LAUNCHER_MARKER     = "# Generated by sad2xs-install-sad. Do not edit."


################################################################################
# Dependency Reporting
################################################################################
########################################
# Missing Dependency Record
########################################
@dataclass(frozen = True)
class MissingDependency:
    """
    One dependency the SAD build needs but the machine does not provide.

    Attributes
    ----------
    name : str
        The missing command, executable, or header.
    reason : str
        Why the SAD installation needs it.
    remedy : str
        What the user can do to provide it: a command on a platform where
        one suffices, or the package that supplies it.
    """
    name:       str
    reason:     str
    remedy:     str


########################################
# Command Check
########################################
def check_command(
        cmd:        str,
        reason:     str,
        remedy:     str,
        path:       str | None = None) -> MissingDependency | None:
    """
    Check that a command can be found.

    Parameters
    ----------
    cmd : str
        Command to search for.
    reason : str
        Why the SAD installation needs the command.
    remedy : str
        What provides it, as reported to the user.
    path : str, optional
        Search this PATH rather than the caller's. Defaults to None.

    Returns
    -------
    MissingDependency or None
        A report when the command cannot be found.
    """
    if shutil.which(cmd, path = path) is not None:
        return None
    return MissingDependency(cmd, reason, remedy)


########################################
# Dependency Gate
########################################
def require_dependencies(
        missing:    list[MissingDependency],
        footer:     str | None = None) -> None:
    """
    Report every missing dependency, and stop before touching SAD.

    Parameters
    ----------
    missing : list of MissingDependency
        Everything the audit could not find.
    footer : str, optional
        Closing instruction, for a platform where installing a system
        package is not something the user can necessarily do alone.
        Defaults to None.

    Raises
    ------
    SystemExit
        If anything the SAD installation needs is missing.
    """
    if not missing:
        logger.info("All required dependencies found")
        return

    lines = ["Missing dependencies required to build SAD:", ""]
    for dependency in missing:
        lines.append(f"  {dependency.name}")
        lines.append(f"      {dependency.reason}")
        lines.append(f"      Remedy: {dependency.remedy}")
        lines.append("")
    lines.append(
        "SAD2XS never installs system dependencies and never uses sudo.")
    lines.append(
        footer or "Install the above yourself, then rerun sad2xs-install-sad.")

    sys.exit("\n".join(lines))

################################################################################
# Build Environment
################################################################################
# A conda environment exports compiler, include, library, and linker settings
# that point at its own toolchain. SAD picks those up and fails to link against
# the platform libraries, so they are stripped rather than overridden.
INHERITED_BUILD_VARIABLES = [
    "CFLAGS", "CXXFLAGS", "FFLAGS", "FCFLAGS",
    "CPPFLAGS", "LDFLAGS", "LDFLAGS_LD",
    "PKG_CONFIG_PATH", "CONDA_BUILD_SYSROOT", "LD_LIBRARY_PATH",
    "CPATH", "C_INCLUDE_PATH", "CPLUS_INCLUDE_PATH", "LIBRARY_PATH",
    "DYLD_LIBRARY_PATH", "DYLD_FALLBACK_LIBRARY_PATH",
    "CONDA_PREFIX", "CONDA_DEFAULT_ENV", "CONDA_SHLVL",
    "CONDA_TOOLCHAIN_HOST", "CONDA_TOOLCHAIN_BUILD",
    "_CONDA_PYTHON_SYSCONFIGDATA_NAME",
    "CC", "CXX", "FC", "F77", "F90",
    "AR", "AS", "LD", "NM", "RANLIB", "STRIP",
    "CMAKE_ARGS", "CMAKE_PREFIX_PATH",
    "CONDA_BUILD", "PREFIX", "BUILD_PREFIX",
    "HOST", "BUILD", "TARGET"]


def strip_inherited_build_settings() -> dict[str, str]:
    """
    Copy the environment with any inherited toolchain settings removed.

    Returns
    -------
    dict
        The caller's environment, less anything that would redirect the
        build away from the platform toolchain.
    """
    env = os.environ.copy()
    for variable in INHERITED_BUILD_VARIABLES:
        env.pop(variable, None)
    return env

################################################################################
# Default Locations
################################################################################
def default_prefix() -> Path:
    """
    Return the default directory for the SAD source tree and build logs.

    Returns
    -------
    Path
        The XDG data directory for this package.
    """
    return (Path.home() / ".local" / "share" / "sad2xs").resolve()


def default_bin_dir() -> Path:
    """
    Return the default directory for the `sad` launcher.

    Debian and RHEL family profiles put `~/.local/bin` on PATH once it
    exists, so the launcher lands somewhere the shell already looks.

    Returns
    -------
    Path
        The XDG user binary directory.
    """
    return (Path.home() / ".local" / "bin").resolve()

################################################################################
# Install Configuration
################################################################################
@dataclass(frozen = True)
class InstallConfig:
    """
    Where SAD is built and installed, and which source is used.

    Parameters
    ----------
    prefix : Path
        Directory holding the SAD source tree and the build logs.
    bin_dir : Path
        Directory the `sad` launcher is written to.
    repo_url : str
        Git URL to clone SAD from.
    branch : str
        Branch to clone.
    branch_explicit : bool
        Whether `branch` came from the user rather than the default. An
        absent default branch falls back to the remote's own default; an
        absent explicit one is an error.
    reuse_clone : bool
        If True, keep an existing source tree instead of replacing it.
    """
    prefix:             Path
    bin_dir:            Path
    repo_url:           str
    branch:             str
    branch_explicit:    bool
    reuse_clone:        bool

    def __post_init__(self) -> None:
        """
        Normalise both directories to absolute, symlink-free paths.

        `write_launcher` bakes `src_dir` into a script that runs from any
        directory, so a relative path would produce a launcher that only
        works from the directory it was installed from.
        """
        object.__setattr__(self, "prefix",  self.prefix.expanduser().resolve())
        object.__setattr__(self, "bin_dir", self.bin_dir.expanduser().resolve())

    @property
    def src_dir(self) -> Path:
        """Path: SAD source tree."""
        return self.prefix / "src"

    @property
    def log_dir(self) -> Path:
        """Path: Directory holding the build logs."""
        return self.prefix / "logs"

    @property
    def build_log(self) -> Path:
        """Path: Log file the build output is teed to."""
        return self.log_dir / "build.log"

    @property
    def transaction_dir(self) -> Path:
        """Path: Fixed location holding an in-progress install."""
        return self.prefix / TRANSACTION_DIR

    @property
    def transaction_record(self) -> Path:
        """Path: Record saying what the in-progress install has to undo."""
        return self.transaction_dir / TRANSACTION_RECORD

    @property
    def staging_dir(self) -> Path:
        """Path: Where a fresh clone lands before it is renamed to `src`."""
        return self.transaction_dir / "staging"

    @property
    def backup_dir(self) -> Path:
        """Path: Where the previous source tree is held until the commit."""
        return self.transaction_dir / "backup"

    @property
    def marker(self) -> Path:
        """Path: Marker identifying the source tree as this installer's."""
        return self.src_dir / INSTALL_MARKER

    @property
    def launcher(self) -> Path:
        """Path: The `sad` launcher script."""
        return self.bin_dir / "sad"

    @property
    def executable(self) -> Path:
        """Path: The SAD binary produced by the build."""
        return self.src_dir / "bin" / "gs"

################################################################################
# Command Error
################################################################################
class CommandError(RuntimeError):
    """
    Raised when a subprocess returns non-zero.

    Parameters
    ----------
    cmd : Iterable[str]
        Command that was run.
    returncode : int
        Return code from the command.
    log_path : Path, optional
        Path to the log file the command wrote to. Defaults to None.
    """
    def __init__(
            self,
            cmd:        Iterable[str],
            returncode: int,
            log_path:   Path | None = None) -> None:
        """
        Record the failed command, its exit status, and any log file.
        """
        self.cmd        = list(cmd)
        self.returncode = returncode
        self.log_path   = log_path

        msg = f"""Command failed ({returncode}): {" ".join(self.cmd)}"""
        if log_path:
            msg += f"\nLog: {log_path}"
        super().__init__(msg)

class RollbackError(RuntimeError):
    """
    Raised when a failed install could not be undone automatically.

    The message names the original failure and the state preserved for
    recovery.
    """


class TransactionStateError(RuntimeError):
    """Raised when an install transaction cannot be interpreted safely."""

################################################################################
# Command Runner
################################################################################

########################################
# Log Tail Reporting
########################################
def _log_tail(log_path: Path, n_lines: int = 120) -> None:
    """
    Log the last lines of a build log, best-effort.

    Called on build failure, where the cause is usually near the end of a
    log far too long to show whole.

    Parameters
    ----------
    log_path : Path
        Path to the log file.
    n_lines : int, optional
        Number of lines to show from the end of the log. Defaults to 120.
    """
    try:
        lines   = log_path.read_text(errors = "replace").splitlines()
    except OSError as error:
        logger.info(f"(could not read log) {log_path}: {error}")
        return

    tail    = lines[-n_lines:]
    logger.info("\n" + "#" * 80)
    logger.info(f"Last {len(tail)} lines of log: {log_path}")
    logger.info("#" * 80)
    for line in tail:
        logger.info(line)
    logger.info("#" * 80 + "\n")

########################################
# Run Shell Commands
########################################
def run(
        cmd:            list[str],
        cwd:            Path | str | None       = None,
        env:            dict[str, str] | None   = None,
        check:          bool                    = True,
        log_path:       Path | None             = None,
        stdin_devnull:  bool                    = False) -> subprocess.CompletedProcess | int:
    """
    Run a shell command.

    Parameters
    ----------
    cmd : list[str]
        Command and arguments to run.
    cwd : Path or str, optional
        Working directory to run the command in. Defaults to None.
    env : dict, optional
        Environment variables to use. Defaults to None.
    check : bool, optional
        If True, raise CommandError on a non-zero return code. Defaults to
        True.
    log_path : Path, optional
        If given, tee stdout/stderr to this file. Defaults to None.
    stdin_devnull : bool, optional
        If True, set stdin to /dev/null. Defaults to False.

    Returns
    -------
    subprocess.CompletedProcess or int
        The completed process, or the return code when `log_path` is given.

    Raises
    ------
    CommandError
        If `check` is True and the command returns non-zero.
    """
    logger.info(f"""▶ Running: {" ".join(cmd)}""")
    if cwd:
        logger.info(f"  cwd: {cwd}")

    stdin = subprocess.DEVNULL if stdin_devnull else None

    if log_path is None:
        process = subprocess.run(       # pylint: disable=subprocess-run-check
            cmd,
            cwd     = str(cwd) if cwd else None,
            env     = env,
            stdin   = stdin)
        if check and process.returncode != 0:
            raise CommandError(cmd, process.returncode)

        return process

    log_path.parent.mkdir(parents = True, exist_ok = True)
    with log_path.open("a") as log_file:
        log_file.write(f"""\n\n$ {" ".join(cmd)}\n""")
        log_file.flush()

        # errors="replace": a compiler in a non-UTF-8 locale would otherwise
        # kill the build with a UnicodeDecodeError over a cosmetic byte.
        with subprocess.Popen(
                cmd,
                cwd     = str(cwd) if cwd else None,
                env     = env,
                text    = True,
                errors  = "replace",
                stdout  = subprocess.PIPE,
                stderr  = subprocess.STDOUT,
                stdin   = stdin,
                bufsize = 1) as process:

            # The build's own output, passed through verbatim rather than
            # logged, and flushed so it stays ordered against the logger's
            # stderr when either is redirected.
            for line in process.stdout:
                sys.stdout.write(line)
                sys.stdout.flush()
                log_file.write(line)
            returncode = process.wait()

    if check and returncode != 0:
        _log_tail(log_path)
        raise CommandError(cmd, returncode, log_path = log_path)
    return returncode

################################################################################
# Source Tree
################################################################################

########################################
# Checkout Inspection
########################################
def _git_value(src_dir: Path, *args: str) -> str | None:
    """
    Read one value out of a git checkout, or None if it cannot be read.

    Parameters
    ----------
    src_dir : Path
        Directory to inspect.
    *args : str
        Arguments following `git -C <src_dir>`.

    Returns
    -------
    str or None
        The trimmed output, or None if the directory is not a checkout or
        git reported an error.
    """
    if not (src_dir / ".git").is_dir():
        return None

    process = subprocess.run(           # pylint: disable=subprocess-run-check
        ["git", "-C", str(src_dir), *args],
        text    = True,
        stdout  = subprocess.PIPE,
        stderr  = subprocess.DEVNULL)
    if process.returncode != 0:
        return None
    return process.stdout.strip()


def _installer_owns_tree(config: InstallConfig) -> bool:
    """
    Return True if the existing source tree is this installer's to replace.

    The marker is the only proof accepted. A matching git origin is not
    enough: a user's own SAD checkout would then be deleted by a reinstall
    that happened to point at the same directory.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.

    Returns
    -------
    bool
        True if the tree may be removed.
    """
    return _tree_is_owned(config.src_dir)

########################################
# Prefix Guard
########################################
def _guard_prefix(config: InstallConfig) -> None:
    """
    Refuse a prefix that cannot be safely written to.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.

    Raises
    ------
    SystemExit
        If the prefix is the user's home directory or a filesystem root.
    """
    # Both sides resolved: where home is reached through a symlink, as on
    # AFS, comparing a resolved prefix to an unresolved home fails open.
    resolved = config.prefix
    if resolved == Path.home().resolve() or resolved == resolved.parent:
        sys.exit(
            f"Refusing to install into {resolved}. Choose a dedicated "
            f"directory, such as {default_prefix()}.")

########################################
# Source Selection
########################################
def _resolve_branch(config: InstallConfig) -> str | None:
    """
    Return the branch to clone, or None to take the remote's default.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.

    Returns
    -------
    str or None
        The branch name, or None when the remote default should be used.

    Raises
    ------
    SystemExit
        If a branch the user asked for by name is absent on the remote. A
        typo would otherwise install unintended source and report success.
    """
    try:
        process = subprocess.run(       # pylint: disable=subprocess-run-check
            ["git", "ls-remote", "--exit-code", "--heads",
             config.repo_url, config.branch],
            text    = True,
            stdout  = subprocess.DEVNULL,
            stderr  = subprocess.PIPE)
    except OSError as error:
        sys.exit(f"Could not run git to query {config.repo_url}: {error}")

    if process.returncode == 0:
        return config.branch

    # git ls-remote --exit-code returns 2 for "queried fine, no such head".
    # Anything else is the remote or the network failing, which must not be
    # reported as a missing branch.
    if process.returncode != NO_MATCHING_REF:
        sys.exit(
            f"Could not query {config.repo_url} for branch "
            f"{config.branch!r} (git exit {process.returncode}).\n"
            f"{process.stderr.strip()}")

    if config.branch_explicit:
        sys.exit(
            f"Branch {config.branch!r} does not exist on {config.repo_url}. "
            f"Check the name, or omit --branch to use the remote default.")

    # The default branch name only: upstream renaming it must not break
    # every install, so defer to whatever the remote calls its default.
    logger.warning(
        f"Branch {config.branch!r} not found on the remote; "
        f"using the remote default branch instead.")
    return None


def _check_reuse_matches_request(config: InstallConfig) -> None:
    """
    Reject reuse of a checkout that is not the requested source.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.

    Raises
    ------
    SystemExit
        If the existing checkout's origin or branch differs from what was
        asked for, which would otherwise build source the user did not
        request while appearing to honour the arguments.
    """
    # Fails closed: an unreadable origin, an empty .git, or a git that will
    # not run all return None, and none of them prove the tree is the source
    # that was asked for.
    origin = _git_value(config.src_dir, "remote", "get-url", "origin")
    if origin != config.repo_url:
        found = origin if origin is not None else "unreadable"
        sys.exit(
            f"{config.src_dir} has origin {found}, not {config.repo_url}. "
            f"Drop --reuse-clone to replace it, or choose another --prefix.")

    if not config.branch_explicit:
        return

    # A detached HEAD reports "HEAD", which is never a branch name a user
    # asked for, so it is refused along with the unreadable cases.
    branch = _git_value(config.src_dir, "rev-parse", "--abbrev-ref", "HEAD")
    if branch != config.branch:
        found = branch if branch is not None else "unreadable"
        sys.exit(
            f"{config.src_dir} is on branch {found}, not {config.branch!r}. "
            f"Drop --reuse-clone to re-clone it, or check out the branch "
            f"yourself.")

########################################
# Clone SAD
########################################
def _tree_is_owned(tree: Path) -> bool:
    """
    Report whether a directory is a source tree this installer created.

    Parameters
    ----------
    tree : Path
        Directory to inspect.

    Returns
    -------
    bool
        True when the tree carries this installer's marker.
    """
    marker = tree / INSTALL_MARKER
    try:
        status = marker.lstat()
    except FileNotFoundError:
        return False
    return stat.S_ISREG(status.st_mode)


def _require_plain_dir(path: Path, what: str) -> bool:
    """
    Check that a path is an ordinary directory, or is not there at all.

    Parameters
    ----------
    path : Path
        Path to inspect.
    what : str
        Name for the path in any message.

    Returns
    -------
    bool
        True when the directory is there and ordinary, False when absent.

    Raises
    ------
    TransactionStateError
        If the path is a symlink or anything other than a directory.
    """
    # lstat, not is_dir: is_dir follows symlinks, and recovery must never
    # follow one out of the prefix and delete what it points at.
    try:
        status = path.lstat()
    except FileNotFoundError:
        return False

    if stat.S_ISLNK(status.st_mode):
        raise TransactionStateError(
            f"The {what} path is a symlink, which this installer never "
            f"creates:\n  {path}")

    if not stat.S_ISDIR(status.st_mode):
        raise TransactionStateError(
            f"The {what} path is not a directory:\n  {path}")

    return True


def _is_plain_file(path: Path) -> bool:
    """
    Report whether a path is a regular file without following a symlink.

    Parameters
    ----------
    path : Path
        Path to inspect.

    Returns
    -------
    bool
        True only for a regular file at the path itself.
    """
    try:
        status = path.lstat()
    except FileNotFoundError:
        return False
    return stat.S_ISREG(status.st_mode)


@dataclass(frozen = True)
class _TransactionState:
    """Validated filesystem state for an unfinished installation."""

    had_previous: bool
    has_backup:   bool
    has_source:   bool

########################################
# Transaction Record
########################################
def _write_transaction_record(config: InstallConfig, had_previous: bool) -> None:
    """
    Record what the transaction will have to undo.

    Whether a source tree existed cannot be re-derived once the transaction
    is under way: a first install and a replacement whose backup has yet to
    be made both have no backup.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.
    had_previous : bool
        Whether a source tree existed when the transaction began.
    """
    record = {"version": TRANSACTION_VERSION, "had_previous": had_previous}

    staging = config.transaction_record.with_name(
        f"{config.transaction_record.name}.tmp")
    staging.write_text(json.dumps(record), encoding = "utf-8")
    os.replace(staging, config.transaction_record)


def _read_transaction_record(config: InstallConfig) -> dict | None:
    """
    Read the transaction record, if it is one this installer wrote.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.

    Returns
    -------
    dict or None
        The record, or None when it is absent, unreadable, malformed, or
        of a version this installer does not know.
    """
    if not _is_plain_file(config.transaction_record):
        return None

    try:
        record = json.loads(
            config.transaction_record.read_text(encoding = "utf-8"))
    except (OSError, ValueError):
        return None

    if not isinstance(record, dict):
        return None
    if record.get("version") != TRANSACTION_VERSION:
        return None
    if not isinstance(record.get("had_previous"), bool):
        return None

    return record


def _load_transaction_state(
        config: InstallConfig) -> _TransactionState | None:
    """
    Validate and describe the active install transaction.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.

    Returns
    -------
    _TransactionState or None
        Validated state, or None when no transaction exists.

    Raises
    ------
    TransactionStateError
        If any ownership proof, path type, or state transition is unsafe.
    """
    if not _require_plain_dir(config.transaction_dir, "transaction"):
        return None

    record = _read_transaction_record(config)
    if record is None:
        raise TransactionStateError(
            f"Found a directory where this installer keeps an install in "
            f"progress, but it carries no plain record this installer "
            f"recognises:\n  {config.transaction_dir}")

    _require_plain_dir(config.staging_dir, "staging")
    has_backup   = _require_plain_dir(config.backup_dir, "backup")
    has_source   = _require_plain_dir(config.src_dir, "source")
    had_previous = record["had_previous"]

    if has_backup and not had_previous:
        raise TransactionStateError(
            f"The transaction says no previous source existed, but a "
            f"backup is present:\n  {config.backup_dir}")

    if has_backup and not _tree_is_owned(config.backup_dir):
        raise TransactionStateError(
            f"Found a held-aside source tree that this installer cannot "
            f"identify as its own:\n  {config.backup_dir}")

    if has_source and not _tree_is_owned(config.src_dir):
        backup_note = (
            f"\nThe previous installation is preserved at:\n  "
            f"{config.backup_dir}" if has_backup else "")
        raise TransactionStateError(
            f"An unfinished install left a source tree this installer "
            f"cannot identify:\n  {config.src_dir}{backup_note}")

    if had_previous and not has_backup and not has_source:
        raise TransactionStateError(
            f"The transaction says a previous source existed, but neither "
            f"it nor its backup can be found:\n  {config.src_dir}\n  "
            f"{config.backup_dir}")

    return _TransactionState(
        had_previous = had_previous,
        has_backup   = has_backup,
        has_source   = has_source)

########################################
# Transaction Reconciliation
########################################
def reconcile_transaction(config: InstallConfig) -> None:
    """
    Finish or undo a transaction an earlier run did not complete.

    The transaction directory has a fixed name and carries its own record,
    so an install killed outright is discoverable rather than lost under a
    random path, and a directory that merely shares the name is never
    mistaken for one of ours.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.

    Raises
    ------
    SystemExit
        If the recovery state cannot be shown to be this installer's. The
        exact paths are printed and nothing is removed.
    RollbackError
        If a validated recovery operation fails. Every relevant state path
        is reported for inspection.
    """
    try:
        state = _load_transaction_state(config)
    except TransactionStateError as error:
        sys.exit(
            f"{error}\nMove the unexpected path aside yourself, then rerun. "
            f"Nothing has been changed.")

    if state is None:
        return

    try:
        ########################################
        # A Previous Tree To Restore
        ########################################
        if state.has_backup:
            logger.warning(
                f"Recovering the installation an earlier run left: "
                f"{config.backup_dir}")
            _restore_backup(config, config.backup_dir)
            _retire_transaction(config)
            logger.info(f"Previous installation restored: {config.src_dir}")
            return

        ########################################
        # Nothing Was Ever Moved
        ########################################
        # The previous tree was still at src when the run died, so only the
        # transaction's own contents have to go.
        if state.had_previous:
            logger.warning(
                f"Discarding an unfinished install: {config.transaction_dir}")
            _retire_transaction(config)
            return

        ########################################
        # A First Install That Never Finished
        ########################################
        # There was nothing here before, so anything at src came from the run
        # that died, and is only removable if it says so itself.
        if state.has_source:
            logger.warning(
                f"Discarding an unfinished first install: {config.src_dir}")
            shutil.rmtree(config.src_dir)

        _retire_transaction(config)
    except (OSError, TransactionStateError) as error:
        raise RollbackError(
            f"Could not recover an unfinished SAD installation:\n  {error}\n"
            f"Inspect these paths before changing anything yourself:\n"
            f"  Source:      {config.src_dir}\n"
            f"  Backup:      {config.backup_dir}\n"
            f"  Transaction: {config.transaction_dir}") from error

########################################
# Backup Restoration
########################################
def _restore_backup(config: InstallConfig, backup: Path) -> None:
    """
    Put a held-aside source tree back, discarding the failed one.

    Every step is checked. The backup is the only copy of a working
    installation, so it is never removed when it cannot be put back.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.
    backup : Path
        The held-aside tree.

    Raises
    ------
    OSError
        If the failed tree cannot be removed, or the backup cannot be
        renamed into place. The backup is left where it is.
    """
    if config.src_dir.exists():
        shutil.rmtree(config.src_dir)
    backup.rename(config.src_dir)

########################################
# Transaction Retirement
########################################
def _retire_transaction(config: InstallConfig) -> None:
    """
    Take the transaction out of play in one step, then clear it up.

    The rename is the commit point. Once it has happened no later run can
    read the directory as rollback state, so clearing up what is left is
    only tidying, and may fail without costing anything.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.
    """
    if not _require_plain_dir(config.transaction_dir, "transaction"):
        return

    holder = Path(tempfile.mkdtemp(dir = config.prefix, prefix = CLEANUP_PREFIX))
    config.transaction_dir.rename(holder / "transaction")

    try:
        shutil.rmtree(holder)
    except OSError as error:
        # The install is already committed, so this is reported rather than
        # raised. Silence would leave an unexplained directory behind.
        logger.warning(f"Could not remove {holder}: {error}")

########################################
# Source Preparation
########################################
def prepare_source(config: InstallConfig) -> bool:
    """
    Put a SAD source tree where the build can run.

    A reused tree is built in place, as `--reuse-clone` asks. Otherwise the
    clone lands in the transaction directory, any previous tree is moved
    into the same transaction, and only then is the new tree renamed to
    its final path.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.

    Returns
    -------
    bool
        Whether an existing tree is being reused.

    Raises
    ------
    SystemExit
        If the prefix is unsafe, if an existing tree is not this
        installer's to replace, or if the requested source cannot be had.
    CommandError
        If the clone returns non-zero. The previous source tree is left
        untouched in that case.

    Notes
    -----
    SAD's build bakes the absolute build directory into the binary, as an
    rpath and in the Tcl/Tk library paths. The tree therefore has to be at
    its final path before make runs, which is why the rename happens here
    and not after the build.
    """
    _guard_prefix(config)

    try:
        has_source = _require_plain_dir(config.src_dir, "source")
    except TransactionStateError as error:
        sys.exit(f"{error}\nNothing has been changed.")

    config.log_dir.mkdir(parents = True, exist_ok = True)

    # Truncated so a failure tail cannot be read from an earlier run. Ahead of
    # the reuse branch, which would otherwise keep appending across rebuilds.
    config.build_log.write_text("")
    logger.info(f"Build log: {config.build_log}")

    if config.reuse_clone and has_source and (
            config.src_dir / ".git").is_dir():
        _check_reuse_matches_request(config)
        logger.info(f"Reusing existing source tree in place: {config.src_dir}")
        return True

    # Everything that can refuse the install runs before anything is moved:
    # a mistyped branch must not cost the user a working installation.
    branch = _resolve_branch(config)
    if has_source and not _installer_owns_tree(config):
        sys.exit(
            f"{config.src_dir} already exists and was not created by this "
            f"installer. Remove it yourself, or choose another --prefix.")

    cmd = ["git", "clone", "--depth", "1"]
    if branch is not None:
        cmd += ["--branch", branch]

    ########################################
    # Open The Transaction
    ########################################
    config.transaction_dir.mkdir(parents = True, exist_ok = True)

    # An interrupted clone leaves nothing at src, so a run killed here has
    # only the transaction directory to discard.
    try:
        _write_transaction_record(config, has_source)
        run(
            cmd + [config.repo_url, str(config.staging_dir)],
            log_path        = config.build_log,
            stdin_devnull   = True)
        (config.staging_dir / INSTALL_MARKER).touch()
    except BaseException:
        _retire_transaction(config)
        raise

    ########################################
    # Move The Previous Tree Aside
    ########################################
    moved = False
    if has_source:
        config.src_dir.rename(config.backup_dir)
        moved = True
        logger.info(f"Previous source tree held aside: {config.backup_dir}")

    try:
        config.staging_dir.rename(config.src_dir)
    except BaseException:
        if moved:
            config.backup_dir.rename(config.src_dir)
        _retire_transaction(config)
        raise

    return False

########################################
# Rollback
########################################
def rollback(
        config: InstallConfig,
        cause:  BaseException) -> None:
    """
    Undo a failed install, or explain exactly what was preserved.

    What has to be undone comes from the transaction record, not from
    guesswork: a first install has no backup to put back, but it does have
    a source tree that only this run created.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.
    cause : BaseException
        The failure being rolled back, named in any rollback error.

    Raises
    ------
    RollbackError
        If the previous state cannot be restored or interpreted safely. The
        preserved transaction path is reported with the original failure.
    """
    try:
        state = _load_transaction_state(config)
    except TransactionStateError as error:
        raise RollbackError(
            f"The install failed:\n  {cause}\n"
            f"Undoing it was refused because the transaction state is not "
            f"safe:\n  {error}\n"
            f"The unfinished transaction has been preserved at:\n"
            f"  {config.transaction_dir}") from cause

    # --reuse-clone opens no transaction: the tree it was told to build in
    # is the only one there is, and there is nothing to put back.
    if state is None:
        return

    try:
        if state.has_backup:
            _restore_backup(config, config.backup_dir)
        elif not state.had_previous and state.has_source:
            # Nothing was here before this run, so the failed tree goes.
            shutil.rmtree(config.src_dir)
    except OSError as error:
        raise RollbackError(
            f"The install failed:\n  {cause}\n"
            f"Undoing it also failed:\n  {error}\n"
            f"The unfinished transaction has been preserved at:\n"
            f"  {config.transaction_dir}\n"
            f"Your previous source tree, if one existed, remains at:\n"
            f"  {config.backup_dir}\n"
            f"Put it back at {config.src_dir} yourself once the cause is "
            f"clear.") from cause

    _retire_transaction(config)

########################################
# Build
################################################################################

########################################
# Make SAD
########################################
def make_sad(
        config:         InstallConfig,
        env:            dict[str, str],
        reused_tree:    bool,
        work_dir:       Path) -> None:
    """
    Run SAD's build steps against a prepared environment.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.
    env : dict
        Environment variables for the build.
    reused_tree : bool
        Whether an existing tree is being reused, as `prepare_source`
        returns.
    work_dir : Path
        Directory to build in.

    Raises
    ------
    CommandError
        If a build step returns non-zero.
    """
    # Only meaningful on a reused tree; a fresh clone has nothing to clean,
    # and upstream's clean target returns non-zero when there is not.
    if reused_tree:
        run(
            ["make", "clean"],
            cwd             = work_dir,
            env             = env,
            log_path        = config.build_log,
            stdin_devnull   = True,
            check           = False)

    for target in ("depend", "exe"):
        run(
            ["make", target],
            cwd             = work_dir,
            env             = env,
            log_path        = config.build_log,
            stdin_devnull   = True)

########################################
# Verify Executable
########################################
def verify_executable(
        config:     InstallConfig,
        work_dir:   Path) -> None:
    """
    Check that the build produced a runnable SAD binary.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.
    work_dir : Path
        Directory the build ran in.

    Raises
    ------
    SystemExit
        If the binary is missing or not executable.
    """
    executable = work_dir / "bin" / "gs"
    if not os.access(executable, os.X_OK):
        sys.exit(
            f"Build finished but {executable} is missing or not "
            f"executable. See {config.build_log}")
    logger.info(f"Build OK: {executable}")

################################################################################
# Source Lifecycle
################################################################################
def install_sad_source(
        config:     InstallConfig,
        env:        dict[str, str],
        prepare:    Callable[[Path], None] | None = None) -> None:
    """
    Install SAD as one transaction: source, build, and launcher together.

    Anything already at the launcher path is checked before a single file
    moves, so an unowned launcher costs no clone and no build. Any previous
    source tree is then held aside for the whole clone, preparation, build,
    and launcher write, and put back if any of them fails.

    `--reuse-clone` rebuilds in place, as it asks, and has no previous tree
    to fall back to.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.
    env : dict
        Environment variables for the build.
    prepare : callable, optional
        Platform-specific preparation, called with the source directory.
        Defaults to None.

    Raises
    ------
    SystemExit
        If the launcher path is occupied, the source cannot be had, or the
        build produced no executable.
    CommandError
        If a build step returns non-zero.
    RollbackError
        If a failure could not be undone. The preserved transaction and
        any previous source location are reported.

    Notes
    -----
    The launcher needs no rollback of its own. It is only replaced once it
    has been shown to be this installer's, the replacement is staged beside
    it and swapped in one step, and it always names the fixed source path,
    so restoring an earlier tree leaves it pointing at the right place.
    """
    ########################################
    # Preflight
    ########################################
    # Both run before anything moves: an unfinished install from an earlier
    # run, or an unowned launcher, must not cost a clone and a build.
    reconcile_transaction(config)
    _launcher_is_replaceable(config.launcher)

    reused_tree = prepare_source(config)

    try:
        if prepare is not None:
            prepare(config.src_dir)
        make_sad(config, env, reused_tree, config.src_dir)
        verify_executable(config, config.src_dir)
        write_launcher(config)
    except BaseException as error:
        rollback(config, error)
        raise

    _retire_transaction(config)

################################################################################
# Launcher
################################################################################
########################################
# Ownership Check
########################################
def _launcher_is_replaceable(launcher: Path) -> None:
    """
    Refuse to replace anything this installer did not write.

    The marker has to be one of the file's own lines. Matching it anywhere
    in the text would accept any script that merely mentions it.

    Parameters
    ----------
    launcher : Path
        The path the launcher would be written to.

    Raises
    ------
    SystemExit
        If something occupies the path that carries no marker.
    """
    # lstat, not exists: a symlink to a missing target still occupies the
    # name, and following it would write through to wherever it points.
    try:
        status = launcher.lstat()
    except FileNotFoundError:
        return

    if stat.S_ISLNK(status.st_mode):
        sys.exit(
            f"{launcher} is a symlink, so it was not written by this "
            f"installer. Remove it yourself, or choose another --bin-dir.")

    if not stat.S_ISREG(status.st_mode):
        sys.exit(
            f"{launcher} is not a regular file. Remove it yourself, or "
            f"choose another --bin-dir.")

    try:
        existing = launcher.read_text(encoding = "utf-8", errors = "replace")
    except OSError as error:
        sys.exit(f"Could not read {launcher}: {error}")

    if LAUNCHER_MARKER not in existing.splitlines():
        sys.exit(
            f"{launcher} already exists and was not written by this "
            f"installer. Remove it yourself, or choose another --bin-dir.")

########################################
# Launcher Text
########################################
def _launcher_text(src_dir: Path) -> str:
    """
    Build the launcher script for a source tree.

    Parameters
    ----------
    src_dir : Path
        The SAD source tree the launcher runs.

    Returns
    -------
    str
        The launcher script.

    Notes
    -----
    1) Called with a file, the launcher runs in batch mode from the caller's
       working directory
    2) Called with no arguments, it runs interactively from the source
       directory, which is where SAD looks for its own support files
    """
    # shlex.quote: the prefix is user-supplied and lands inside shell source,
    # where a quote or $( ) would break the script or be evaluated.
    quoted = shlex.quote(str(src_dir))

    # python3 rather than realpath(1), which older macOS does not ship.
    return f"""#!/usr/bin/env bash
{LAUNCHER_MARKER}
set -e
SAD_DIR={quoted}
GS_EXEC="$SAD_DIR/bin/gs"
CALL_DIR="$(pwd)"

if [[ $# -gt 0 ]]; then
    if [[ "$1" = /* ]]; then
        SAD_INPUT="$1"
    else
        SAD_INPUT="$(python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$CALL_DIR/$1")"
    fi
    shift
    cd "$CALL_DIR" || exit 1
    exec "$GS_EXEC" "$SAD_INPUT" "$@"
else
    cd "$SAD_DIR" || exit 1
    exec "$GS_EXEC"
fi
"""

########################################
# Launcher Installation
########################################
def write_launcher(config: InstallConfig) -> None:
    """
    Write the `sad` launcher script.

    Anything already at the path is inspected first, without following a
    symlink, and only a launcher this installer wrote is replaced. The
    replacement is staged beside it and swapped in one step, so an
    interrupted write cannot leave a half-written script on PATH.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.

    Raises
    ------
    SystemExit
        If the path is occupied by something this installer did not write.
    """
    _launcher_is_replaceable(config.launcher)

    config.bin_dir.mkdir(parents = True, exist_ok = True)

    handle, staging_name = tempfile.mkstemp(
        dir     = config.bin_dir,
        prefix  = ".sad-staging-")
    staging = Path(staging_name)
    try:
        with os.fdopen(handle, "w", encoding = "utf-8") as staged:
            staged.write(_launcher_text(config.src_dir))
        staging.chmod(0o755)
        os.replace(staging, config.launcher)
    except BaseException:
        staging.unlink(missing_ok = True)
        raise

    logger.info(f"Launcher written: {config.launcher}")

################################################################################
# PATH Reporting
################################################################################
def report_path_setup(config: InstallConfig) -> None:
    """
    Report whether the launcher directory is reachable from the shell.

    Shell configuration is never modified. Editing a user's rc file is
    invasive, and a throwaway `--bin-dir` would leave a permanent entry
    behind pointing at a directory that need not outlive the shell.

    Parameters
    ----------
    config : InstallConfig
        Install configuration.
    """
    bin_dir = str(config.bin_dir)

    # Membership of bin_dir in PATH is not enough: an earlier entry can carry
    # its own sad, and that is the one the shell would run.
    found = shutil.which("sad")
    if found is not None and Path(found).resolve() == config.launcher.resolve():
        logger.info(f"sad resolves to {config.launcher}")
        return

    # Quoted because these lines are meant to be pasted into a shell, and the
    # directory came from --bin-dir.
    if bin_dir not in os.environ.get("PATH", "").split(os.pathsep):
        logger.warning(f"{bin_dir} is not on PATH")
        logger.info(
            f"Add it by appending this line to your shell configuration:\n"
            f'  export PATH={shlex.quote(bin_dir)}:"$PATH"')
        return

    if found is None:
        logger.warning(f"{bin_dir} is on PATH but sad does not resolve from it")
    else:
        logger.warning(f"sad resolves to {found}, not the launcher just written")
    logger.info(
        f"Put {bin_dir} first so the new launcher wins:\n"
        f'  export PATH={shlex.quote(bin_dir)}:"$PATH"')
