name: Tests 001 Drift

on:
  # Run after your "Docker Rebuild" workflow completes successfully
  workflow_run:
    workflows: [ "Docker Rebuild" ]
    types: [ completed ]
  # Also run nightly
  schedule:
    - cron: '0 2 * * *'   # daily at 02:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read
  packages: read

concurrency:
  group: tests-001-drift-${{ github.ref }}
  cancel-in-progress: true

jobs:
  drift:
    # if triggered by workflow_run, only run when rebuild succeeded
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/_test_template.yml
    with:
      pull_tag: latest
      test_files: |
        # List the relevant tests here (exact paths)
        tests/test_001_drift.py
    secrets: inherit
